import jsPDF from 'jspdf'

export class PDFService {
  generateEstimatePDF(estimate, project, user) {
    const pdf = new jsPDF()
    const pageWidth = pdf.internal.pageSize.width
    const margin = 20
    let yPosition = margin

    // Header
    pdf.setFontSize(20)
    pdf.setFont(undefined, 'bold')
    pdf.text(user.companyName || 'PhotoQuote AI', margin, yPosition)
    
    yPosition += 10
    pdf.setFontSize(12)
    pdf.setFont(undefined, 'normal')
    pdf.text('Professional Construction Estimate', margin, yPosition)

    yPosition += 20

    // Project Information
    pdf.setFontSize(14)
    pdf.setFont(undefined, 'bold')
    pdf.text('Project Details', margin, yPosition)
    
    yPosition += 10
    pdf.setFontSize(10)
    pdf.setFont(undefined, 'normal')
    pdf.text(`Client: ${project.clientName}`, margin, yPosition)
    
    yPosition += 5
    pdf.text(`Address: ${project.jobSiteAddress}`, margin, yPosition)
    
    yPosition += 5
    pdf.text(`Estimate Date: ${new Date(estimate.generatedOn).toLocaleDateString()}`, margin, yPosition)

    yPosition += 20

    // Materials Table
    pdf.setFontSize(14)
    pdf.setFont(undefined, 'bold')
    pdf.text('Materials & Labor Breakdown', margin, yPosition)
    
    yPosition += 15

    // Table header
    pdf.setFontSize(10)
    pdf.setFont(undefined, 'bold')
    const colWidths = [80, 20, 30, 30]
    const cols = ['Description', 'Qty', 'Unit Cost', 'Total']
    
    let xPosition = margin
    cols.forEach((col, index) => {
      pdf.text(col, xPosition, yPosition)
      xPosition += colWidths[index]
    })

    yPosition += 8
    pdf.line(margin, yPosition, pageWidth - margin, yPosition)
    yPosition += 5

    // Table rows
    pdf.setFont(undefined, 'normal')
    
    // Materials
    estimate.materials?.forEach(material => {
      if (yPosition > 250) {
        pdf.addPage()
        yPosition = margin
      }
      
      xPosition = margin
      pdf.text(material.name || 'Material', xPosition, yPosition)
      xPosition += colWidths[0]
      
      pdf.text(String(material.quantity || 1), xPosition, yPosition)
      xPosition += colWidths[1]
      
      pdf.text(`$${(material.unitCost || 0).toFixed(2)}`, xPosition, yPosition)
      xPosition += colWidths[2]
      
      pdf.text(`$${(material.totalCost || 0).toFixed(2)}`, xPosition, yPosition)
      
      yPosition += 6
    })

    // Labor
    yPosition += 5
    xPosition = margin
    pdf.text('Labor Hours', xPosition, yPosition)
    xPosition += colWidths[0]
    
    pdf.text(String(estimate.laborHours || 0), xPosition, yPosition)
    xPosition += colWidths[1]
    
    const laborRate = 65
    pdf.text(`$${laborRate.toFixed(2)}/hr`, xPosition, yPosition)
    xPosition += colWidths[2]
    
    const laborTotal = (estimate.laborHours || 0) * laborRate
    pdf.text(`$${laborTotal.toFixed(2)}`, xPosition, yPosition)

    yPosition += 15
    pdf.line(margin, yPosition, pageWidth - margin, yPosition)
    yPosition += 10

    // Total
    pdf.setFontSize(14)
    pdf.setFont(undefined, 'bold')
    pdf.text(`Total Estimate: $${(estimate.totalCost || 0).toLocaleString()}`, margin, yPosition)

    yPosition += 20

    // Footer
    pdf.setFontSize(8)
    pdf.setFont(undefined, 'normal')
    pdf.text('This estimate is valid for 30 days and subject to material price changes.', margin, yPosition)
    
    yPosition += 5
    pdf.text('Generated by PhotoQuote AI - Professional estimates from photos.', margin, yPosition)

    return pdf
  }

  downloadPDF(pdf, filename = 'estimate.pdf') {
    pdf.save(filename)
  }
}

export const pdfService = new PDFService()